const { GoogleGenAI } = require('@google/genai');
const Doctor = require('../models/Doctor');
const Specialty = require('../models/Specialty');

const analyzeSymptoms = async (req, res) => {
    try {
        const { query } = req.body;
        if (!query) {
            return res.status(400).json({ message: 'Query is required' });
        }

        if (!process.env.GEMINI_API_KEY) {
            return res.status(500).json({ message: 'AI Assistant is currently unavailable. API key missing.' });
        }

        const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

        // Get available specialties from DB to guide the AI
        const specialties = await Specialty.find().select('name');
        const specialtyNames = specialties.map(s => s.name).join(', ');

        const prompt = `
        You are an intelligent medical triage assistant. A user has provided the following symptoms: "${query}".
        Analyze these symptoms and provide:
        1. A list of 2-3 possible conditions (keep it general and non-diagnostic).
        2. The most appropriate medical specialty for this condition. IMPORTANT: Output the title of the *Specialist* (e.g., "Dermatologist" instead of "Dermatology", "Cardiologist" instead of "Cardiology"). If possible, exactly match one from this list: ${specialtyNames}.

        Always include the following disclaimer exactly: "Responses are generated by an AI system and may not be fully accurate. This is not a medical diagnosis. Please consult a doctor."

        Respond strictly in JSON format matching this schema:
        {
          "possibleConditions": ["condition1", "condition2"],
          "recommendedSpecialty": "specialty name",
          "disclaimer": "The disclaimer text"
        }
        `;

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
            config: {
                responseMimeType: 'application/json'
            }
        });

        const resultText = response.text;
        const resultJSON = JSON.parse(resultText);

        // Implement a fuzzy regex using the primary root characters (e.g., "Dermat" correctly intercepts both "Dermatology" and "Dermatologist")
        const specialtyPrefix = resultJSON.recommendedSpecialty.replace(/[^a-zA-Z]/g, '').substring(0, 6);

        // Fetch top-rated doctors matching the suggested specialty WITH tracked availability
        const doctors = await Doctor.find({
            specialty: { $regex: new RegExp(specialtyPrefix, 'i') },
            'availability.0': { $exists: true } // Meaning they have at least 1 day configured
        })
        .sort({ averageRating: -1, totalReviews: -1 })
        .limit(3)
        .select('name specialty profilePhoto averageRating totalReviews experienceYears consultationFee availability');

        res.status(200).json({
            analysis: resultJSON,
            doctors
        });

    } catch (error) {
        console.error('AI Analysis Error:', error);
        res.status(500).json({ message: 'Failed to analyze symptoms. Please try again later.' });
    }
};

module.exports = { analyzeSymptoms };
